# MongoDB Configuration - Connects to MongoDB Atlas
spring.data.mongodb.uri=mongodb://parikshithsr19:Pari12345@ac-lbrgqy7-shard-00-00.oiqbdde.mongodb.net:27017,ac-lbrgqy7-shard-00-01.oiqbdde.mongodb.net:27017,ac-lbrgqy7-shard-00-02.oiqbdde.mongodb.net:27017/?ssl=true&replicaSet=atlas-3skpne-shard-0&authSource=admin&appName=Cluster0MentalWellness
spring.data.mongodb.database=mentalwellness
spring.data.mongodb.auto-index-creation=true
